// Server-only: builds a PDF for any client_documents row.
// Uses existing intake builders where available; otherwise renders a
// simple "DRAFT — pending attorney review" form with the client info.

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { buildIntakePdfs } from "@/lib/email/intake-pdfs.server";
import { buildJs44Pdf } from "@/lib/email/js44.server";
import { buildMotionReferralPdf } from "@/lib/email/motion-referral.server";

function s(v: unknown): string {
  if (v == null) return "";
  return String(v);
}

async function buildSyntheticAnswers(clientId: string): Promise<Record<string, unknown>> {
  const [{ data: client }, { data: contacts }] = await Promise.all([
    supabaseAdmin
      .from("app_clients")
      .select("full_name, email, phone_e164, place_of_birth, country_of_origin, language")
      .eq("id", clientId)
      .maybeSingle(),
    supabaseAdmin
      .from("client_contacts")
      .select("name, phone_e164, email, relationship, priority")
      .eq("client_id", clientId)
      .order("priority", { ascending: true }),
  ]);
  const c = (client ?? {}) as any;
  const cs = (contacts ?? []) as any[];
  const primary = cs[0] ?? {};
  const secondary = cs[1] ?? {};
  return {
    full_name: s(c.full_name),
    contact_email: s(c.email),
    contact_phone: s(c.phone_e164),
    place_of_birth: s(c.place_of_birth),
    country_of_citizenship: s(c.country_of_origin),
    country_of_origin: s(c.country_of_origin),
    emergency_contact_name: s(primary.name),
    emergency_contact_phone: s(primary.phone_e164),
    emergency_contact_email: s(primary.email),
    emergency_contact_relation: s(primary.relationship),
    emergency_contact_2_name: s(secondary.name),
    emergency_contact_2_phone: s(secondary.phone_e164),
    emergency_contact_2_email: s(secondary.email),
    emergency_contact_2_relation: s(secondary.relationship),
  };
}

async function buildStubPdf(title: string, clientInfo: Record<string, string>): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // Letter
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  const margin = 54;

  let y = height - margin;
  page.drawText(title, { x: margin, y, font: bold, size: 16, color: rgb(0, 0, 0) });
  y -= 28;

  page.drawText("DRAFT — Pending attorney review", {
    x: margin,
    y,
    font: bold,
    size: 11,
    color: rgb(0.7, 0, 0),
  });
  y -= 20;

  const intro =
    "This form was generated from the client's intake answers and is pending review " +
    "by counsel. The fields below summarize what the client provided. Once the attorney " +
    "approves this draft, the finalized form will replace this document.";
  for (const line of wrapText(intro, font, 11, width - margin * 2)) {
    page.drawText(line, { x: margin, y, font, size: 11, color: rgb(0, 0, 0) });
    y -= 16;
  }
  y -= 12;

  page.drawText("Client information on file", { x: margin, y, font: bold, size: 12 });
  y -= 18;

  for (const [k, v] of Object.entries(clientInfo)) {
    if (y < margin + 40) break;
    page.drawText(`${k}:`, { x: margin, y, font: bold, size: 10 });
    page.drawText(v || "—", { x: margin + 160, y, font, size: 10 });
    y -= 14;
  }

  y = margin + 20;
  page.drawText("Generated by DetencionDefensa — Draft document, not for filing.", {
    x: margin,
    y,
    font,
    size: 9,
    color: rgb(0.45, 0.45, 0.45),
  });

  return await doc.save();
}

function wrapText(text: string, font: any, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    const trial = current ? `${current} ${w}` : w;
    if (font.widthOfTextAtSize(trial, size) > maxWidth) {
      if (current) lines.push(current);
      current = w;
    } else {
      current = trial;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export async function buildDocumentPdf(documentId: string): Promise<{
  bytes: Uint8Array;
  filename: string;
}> {
  const { data: doc, error } = await supabaseAdmin
    .from("client_documents")
    .select("id, client_id, title, content, document_type")
    .eq("id", documentId)
    .maybeSingle();
  if (error || !doc) throw new Error("Document not found");
  const d = doc as any;

  const answers = await buildSyntheticAnswers(d.client_id);
  const safeTitle = (d.title ?? "document").replace(/[^a-z0-9]+/gi, "_");
  const filename = `${safeTitle}.pdf`;

  // Route by document_type to the right builder
  switch (d.document_type as string) {
    case "ao_242":
    case "habeas_ao242": {
      const { habeas } = await buildIntakePdfs(answers as any);
      return { bytes: habeas, filename };
    }
    case "ao_240":
    case "ao240_ifp": {
      const { ifp } = await buildIntakePdfs(answers as any);
      return { bytes: ifp, filename };
    }
    case "civil_cover_sheet":
    case "js44": {
      const bytes = await buildJs44Pdf(answers as Record<string, unknown>);
      return { bytes, filename };
    }
    case "motion_for_counsel":
    case "motion_counsel": {
      const bytes = await buildMotionReferralPdf(answers as any);
      return { bytes, filename };
    }
    default: {
      const info: Record<string, string> = {
        "Full name": s(answers.full_name),
        "Email": s(answers.contact_email),
        "Phone": s(answers.contact_phone),
        "Place of birth": s(answers.place_of_birth),
        "Country of origin": s(answers.country_of_origin),
        "Emergency contact": s(answers.emergency_contact_name),
        "Emergency phone": s(answers.emergency_contact_phone),
        "Emergency relationship": s(answers.emergency_contact_relation),
      };
      const bytes = await buildStubPdf(d.title ?? "Draft document", info);
      return { bytes, filename };
    }
  }
}
