/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SentinelTrustRouteImport } from './routes/sentinel-trust'
import { Route as OwnPropertyRouteImport } from './routes/own-property'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as AltRouteImport } from './routes/alt'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as ReadinessStartRouteImport } from './routes/readiness/start'
import { Route as ReadinessSignRouteImport } from './routes/readiness/sign'
import { Route as ReadinessReviewRouteImport } from './routes/readiness/review'
import { Route as ReadinessIntakeRouteImport } from './routes/readiness/intake'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicEmergencyActivateRouteImport } from './routes/api/public/emergency/activate'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelTrustRoute = SentinelTrustRouteImport.update({
  id: '/sentinel-trust',
  path: '/sentinel-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnPropertyRoute = OwnPropertyRouteImport.update({
  id: '/own-property',
  path: '/own-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AltRoute = AltRouteImport.update({
  id: '/alt',
  path: '/alt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessStartRoute = ReadinessStartRouteImport.update({
  id: '/readiness/start',
  path: '/readiness/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessSignRoute = ReadinessSignRouteImport.update({
  id: '/readiness/sign',
  path: '/readiness/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessReviewRoute = ReadinessReviewRouteImport.update({
  id: '/readiness/review',
  path: '/readiness/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessIntakeRoute = ReadinessIntakeRouteImport.update({
  id: '/readiness/intake',
  path: '/readiness/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmergencyActivateRoute =
  ApiPublicEmergencyActivateRouteImport.update({
    id: '/api/public/emergency/activate',
    path: '/api/public/emergency/activate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/own-property': typeof OwnPropertyRoute
  '/sentinel-trust': typeof SentinelTrustRoute
  '/splash': typeof SplashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/readiness/intake': typeof ReadinessIntakeRoute
  '/readiness/review': typeof ReadinessReviewRoute
  '/readiness/sign': typeof ReadinessSignRoute
  '/readiness/start': typeof ReadinessStartRoute
  '/track/$token': typeof TrackTokenRoute
  '/api/public/emergency/activate': typeof ApiPublicEmergencyActivateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/own-property': typeof OwnPropertyRoute
  '/sentinel-trust': typeof SentinelTrustRoute
  '/splash': typeof SplashRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/readiness/intake': typeof ReadinessIntakeRoute
  '/readiness/review': typeof ReadinessReviewRoute
  '/readiness/sign': typeof ReadinessSignRoute
  '/readiness/start': typeof ReadinessStartRoute
  '/track/$token': typeof TrackTokenRoute
  '/api/public/emergency/activate': typeof ApiPublicEmergencyActivateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/alt': typeof AltRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/own-property': typeof OwnPropertyRoute
  '/sentinel-trust': typeof SentinelTrustRoute
  '/splash': typeof SplashRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/readiness/intake': typeof ReadinessIntakeRoute
  '/readiness/review': typeof ReadinessReviewRoute
  '/readiness/sign': typeof ReadinessSignRoute
  '/readiness/start': typeof ReadinessStartRoute
  '/track/$token': typeof TrackTokenRoute
  '/api/public/emergency/activate': typeof ApiPublicEmergencyActivateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alt'
    | '/app'
    | '/checkout'
    | '/coming-soon'
    | '/intake'
    | '/login'
    | '/own-property'
    | '/sentinel-trust'
    | '/splash'
    | '/dashboard'
    | '/auth/callback'
    | '/readiness/intake'
    | '/readiness/review'
    | '/readiness/sign'
    | '/readiness/start'
    | '/track/$token'
    | '/api/public/emergency/activate'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alt'
    | '/app'
    | '/checkout'
    | '/coming-soon'
    | '/intake'
    | '/login'
    | '/own-property'
    | '/sentinel-trust'
    | '/splash'
    | '/dashboard'
    | '/auth/callback'
    | '/readiness/intake'
    | '/readiness/review'
    | '/readiness/sign'
    | '/readiness/start'
    | '/track/$token'
    | '/api/public/emergency/activate'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alt'
    | '/app'
    | '/checkout'
    | '/coming-soon'
    | '/intake'
    | '/login'
    | '/own-property'
    | '/sentinel-trust'
    | '/splash'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/readiness/intake'
    | '/readiness/review'
    | '/readiness/sign'
    | '/readiness/start'
    | '/track/$token'
    | '/api/public/emergency/activate'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AltRoute: typeof AltRoute
  AppRoute: typeof AppRoute
  CheckoutRoute: typeof CheckoutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  OwnPropertyRoute: typeof OwnPropertyRoute
  SentinelTrustRoute: typeof SentinelTrustRoute
  SplashRoute: typeof SplashRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ReadinessIntakeRoute: typeof ReadinessIntakeRoute
  ReadinessReviewRoute: typeof ReadinessReviewRoute
  ReadinessSignRoute: typeof ReadinessSignRoute
  ReadinessStartRoute: typeof ReadinessStartRoute
  TrackTokenRoute: typeof TrackTokenRoute
  ApiPublicEmergencyActivateRoute: typeof ApiPublicEmergencyActivateRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinel-trust': {
      id: '/sentinel-trust'
      path: '/sentinel-trust'
      fullPath: '/sentinel-trust'
      preLoaderRoute: typeof SentinelTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/own-property': {
      id: '/own-property'
      path: '/own-property'
      fullPath: '/own-property'
      preLoaderRoute: typeof OwnPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alt': {
      id: '/alt'
      path: '/alt'
      fullPath: '/alt'
      preLoaderRoute: typeof AltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/start': {
      id: '/readiness/start'
      path: '/readiness/start'
      fullPath: '/readiness/start'
      preLoaderRoute: typeof ReadinessStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/sign': {
      id: '/readiness/sign'
      path: '/readiness/sign'
      fullPath: '/readiness/sign'
      preLoaderRoute: typeof ReadinessSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/review': {
      id: '/readiness/review'
      path: '/readiness/review'
      fullPath: '/readiness/review'
      preLoaderRoute: typeof ReadinessReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/intake': {
      id: '/readiness/intake'
      path: '/readiness/intake'
      fullPath: '/readiness/intake'
      preLoaderRoute: typeof ReadinessIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emergency/activate': {
      id: '/api/public/emergency/activate'
      path: '/api/public/emergency/activate'
      fullPath: '/api/public/emergency/activate'
      preLoaderRoute: typeof ApiPublicEmergencyActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AltRoute: AltRoute,
  AppRoute: AppRoute,
  CheckoutRoute: CheckoutRoute,
  ComingSoonRoute: ComingSoonRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  OwnPropertyRoute: OwnPropertyRoute,
  SentinelTrustRoute: SentinelTrustRoute,
  SplashRoute: SplashRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ReadinessIntakeRoute: ReadinessIntakeRoute,
  ReadinessReviewRoute: ReadinessReviewRoute,
  ReadinessSignRoute: ReadinessSignRoute,
  ReadinessStartRoute: ReadinessStartRoute,
  TrackTokenRoute: TrackTokenRoute,
  ApiPublicEmergencyActivateRoute: ApiPublicEmergencyActivateRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
