/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SentinelTrustRouteImport } from './routes/sentinel-trust'
import { Route as RetainerRouteImport } from './routes/retainer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PastorsRouteImport } from './routes/pastors'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OwnPropertyRouteImport } from './routes/own-property'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DagRouteImport } from './routes/dag'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AttorneyRouteImport } from './routes/attorney'
import { Route as AppRouteImport } from './routes/app'
import { Route as AltRouteImport } from './routes/alt'
import { Route as FirmRouteImport } from './routes/_firm'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as ReadinessStartRouteImport } from './routes/readiness/start'
import { Route as ReadinessSignRouteImport } from './routes/readiness/sign'
import { Route as ReadinessReviewRouteImport } from './routes/readiness/review'
import { Route as ReadinessIntakeRouteImport } from './routes/readiness/intake'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSendAdminInviteRouteImport } from './routes/api/public/send-admin-invite'
import { Route as ApiPublicMailFromCheckRouteImport } from './routes/api/public/mail-from-check'
import { Route as FirmFirmQueueRouteImport } from './routes/_firm/firm.queue'
import { Route as AuthenticatedCaseIdRouteImport } from './routes/_authenticated/case.$id'
import { Route as AdminAdminTriggersRouteImport } from './routes/_admin/admin.triggers'
import { Route as AdminAdminRemindersRouteImport } from './routes/_admin/admin.reminders'
import { Route as AdminAdminClientsRouteImport } from './routes/_admin/admin.clients'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicEmergencyTestMirrorRouteImport } from './routes/api/public/emergency/test-mirror'
import { Route as ApiPublicEmergencyActivateRouteImport } from './routes/api/public/emergency/activate'
import { Route as ApiPublicDevSendInstallRouteImport } from './routes/api/public/dev/send-install'
import { Route as ApiPublicCronProcessDueActivationsRouteImport } from './routes/api/public/cron/process-due-activations'
import { Route as FirmFirmReviewIdRouteImport } from './routes/_firm/firm.review.$id'
import { Route as AdminAdminClientsIdRouteImport } from './routes/_admin/admin.clients.$id'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelTrustRoute = SentinelTrustRouteImport.update({
  id: '/sentinel-trust',
  path: '/sentinel-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const RetainerRoute = RetainerRouteImport.update({
  id: '/retainer',
  path: '/retainer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PastorsRoute = PastorsRouteImport.update({
  id: '/pastors',
  path: '/pastors',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnPropertyRoute = OwnPropertyRouteImport.update({
  id: '/own-property',
  path: '/own-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DagRoute = DagRouteImport.update({
  id: '/dag',
  path: '/dag',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AttorneyRoute = AttorneyRouteImport.update({
  id: '/attorney',
  path: '/attorney',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AltRoute = AltRouteImport.update({
  id: '/alt',
  path: '/alt',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmRoute = FirmRouteImport.update({
  id: '/_firm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessStartRoute = ReadinessStartRouteImport.update({
  id: '/readiness/start',
  path: '/readiness/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessSignRoute = ReadinessSignRouteImport.update({
  id: '/readiness/sign',
  path: '/readiness/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessReviewRoute = ReadinessReviewRouteImport.update({
  id: '/readiness/review',
  path: '/readiness/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessIntakeRoute = ReadinessIntakeRouteImport.update({
  id: '/readiness/intake',
  path: '/readiness/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendAdminInviteRoute =
  ApiPublicSendAdminInviteRouteImport.update({
    id: '/api/public/send-admin-invite',
    path: '/api/public/send-admin-invite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMailFromCheckRoute = ApiPublicMailFromCheckRouteImport.update({
  id: '/api/public/mail-from-check',
  path: '/api/public/mail-from-check',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmFirmQueueRoute = FirmFirmQueueRouteImport.update({
  id: '/firm/queue',
  path: '/firm/queue',
  getParentRoute: () => FirmRoute,
} as any)
const AuthenticatedCaseIdRoute = AuthenticatedCaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminTriggersRoute = AdminAdminTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRemindersRoute = AdminAdminRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClientsRoute = AdminAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminAdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmergencyTestMirrorRoute =
  ApiPublicEmergencyTestMirrorRouteImport.update({
    id: '/api/public/emergency/test-mirror',
    path: '/api/public/emergency/test-mirror',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmergencyActivateRoute =
  ApiPublicEmergencyActivateRouteImport.update({
    id: '/api/public/emergency/activate',
    path: '/api/public/emergency/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevSendInstallRoute = ApiPublicDevSendInstallRouteImport.update({
  id: '/api/public/dev/send-install',
  path: '/api/public/dev/send-install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronProcessDueActivationsRoute =
  ApiPublicCronProcessDueActivationsRouteImport.update({
    id: '/api/public/cron/process-due-activations',
    path: '/api/public/cron/process-due-activations',
    getParentRoute: () => rootRouteImport,
  } as any)
const FirmFirmReviewIdRoute = FirmFirmReviewIdRouteImport.update({
  id: '/firm/review/$id',
  path: '/firm/review/$id',
  getParentRoute: () => FirmRoute,
} as any)
const AdminAdminClientsIdRoute = AdminAdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
  '/app': typeof AppRoute
  '/attorney': typeof AttorneyRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dag': typeof DagRoute
  '/download': typeof DownloadRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/own-property': typeof OwnPropertyRoute
  '/partners': typeof PartnersRoute
  '/pastors': typeof PastorsRoute
  '/privacy': typeof PrivacyRoute
  '/retainer': typeof RetainerRoute
  '/sentinel-trust': typeof SentinelTrustRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splash': typeof SplashRoute
  '/support': typeof SupportRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/venues': typeof VenuesRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/cases': typeof AuthenticatedCasesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/readiness/intake': typeof ReadinessIntakeRoute
  '/readiness/review': typeof ReadinessReviewRoute
  '/readiness/sign': typeof ReadinessSignRoute
  '/readiness/start': typeof ReadinessStartRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin/clients': typeof AdminAdminClientsRouteWithChildren
  '/admin/reminders': typeof AdminAdminRemindersRoute
  '/admin/triggers': typeof AdminAdminTriggersRoute
  '/case/$id': typeof AuthenticatedCaseIdRoute
  '/firm/queue': typeof FirmFirmQueueRoute
  '/api/public/mail-from-check': typeof ApiPublicMailFromCheckRoute
  '/api/public/send-admin-invite': typeof ApiPublicSendAdminInviteRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/clients/$id': typeof AdminAdminClientsIdRoute
  '/firm/review/$id': typeof FirmFirmReviewIdRoute
  '/api/public/cron/process-due-activations': typeof ApiPublicCronProcessDueActivationsRoute
  '/api/public/dev/send-install': typeof ApiPublicDevSendInstallRoute
  '/api/public/emergency/activate': typeof ApiPublicEmergencyActivateRoute
  '/api/public/emergency/test-mirror': typeof ApiPublicEmergencyTestMirrorRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alt': typeof AltRoute
  '/app': typeof AppRoute
  '/attorney': typeof AttorneyRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dag': typeof DagRoute
  '/download': typeof DownloadRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/own-property': typeof OwnPropertyRoute
  '/partners': typeof PartnersRoute
  '/pastors': typeof PastorsRoute
  '/privacy': typeof PrivacyRoute
  '/retainer': typeof RetainerRoute
  '/sentinel-trust': typeof SentinelTrustRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splash': typeof SplashRoute
  '/support': typeof SupportRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/venues': typeof VenuesRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/cases': typeof AuthenticatedCasesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/readiness/intake': typeof ReadinessIntakeRoute
  '/readiness/review': typeof ReadinessReviewRoute
  '/readiness/sign': typeof ReadinessSignRoute
  '/readiness/start': typeof ReadinessStartRoute
  '/track/$token': typeof TrackTokenRoute
  '/admin/clients': typeof AdminAdminClientsRouteWithChildren
  '/admin/reminders': typeof AdminAdminRemindersRoute
  '/admin/triggers': typeof AdminAdminTriggersRoute
  '/case/$id': typeof AuthenticatedCaseIdRoute
  '/firm/queue': typeof FirmFirmQueueRoute
  '/api/public/mail-from-check': typeof ApiPublicMailFromCheckRoute
  '/api/public/send-admin-invite': typeof ApiPublicSendAdminInviteRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/clients/$id': typeof AdminAdminClientsIdRoute
  '/firm/review/$id': typeof FirmFirmReviewIdRoute
  '/api/public/cron/process-due-activations': typeof ApiPublicCronProcessDueActivationsRoute
  '/api/public/dev/send-install': typeof ApiPublicDevSendInstallRoute
  '/api/public/emergency/activate': typeof ApiPublicEmergencyActivateRoute
  '/api/public/emergency/test-mirror': typeof ApiPublicEmergencyTestMirrorRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_firm': typeof FirmRouteWithChildren
  '/alt': typeof AltRoute
  '/app': typeof AppRoute
  '/attorney': typeof AttorneyRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dag': typeof DagRoute
  '/download': typeof DownloadRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/own-property': typeof OwnPropertyRoute
  '/partners': typeof PartnersRoute
  '/pastors': typeof PastorsRoute
  '/privacy': typeof PrivacyRoute
  '/retainer': typeof RetainerRoute
  '/sentinel-trust': typeof SentinelTrustRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splash': typeof SplashRoute
  '/support': typeof SupportRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/venues': typeof VenuesRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/readiness/intake': typeof ReadinessIntakeRoute
  '/readiness/review': typeof ReadinessReviewRoute
  '/readiness/sign': typeof ReadinessSignRoute
  '/readiness/start': typeof ReadinessStartRoute
  '/track/$token': typeof TrackTokenRoute
  '/_admin/admin/clients': typeof AdminAdminClientsRouteWithChildren
  '/_admin/admin/reminders': typeof AdminAdminRemindersRoute
  '/_admin/admin/triggers': typeof AdminAdminTriggersRoute
  '/_authenticated/case/$id': typeof AuthenticatedCaseIdRoute
  '/_firm/firm/queue': typeof FirmFirmQueueRoute
  '/api/public/mail-from-check': typeof ApiPublicMailFromCheckRoute
  '/api/public/send-admin-invite': typeof ApiPublicSendAdminInviteRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_admin/admin/clients/$id': typeof AdminAdminClientsIdRoute
  '/_firm/firm/review/$id': typeof FirmFirmReviewIdRoute
  '/api/public/cron/process-due-activations': typeof ApiPublicCronProcessDueActivationsRoute
  '/api/public/dev/send-install': typeof ApiPublicDevSendInstallRoute
  '/api/public/emergency/activate': typeof ApiPublicEmergencyActivateRoute
  '/api/public/emergency/test-mirror': typeof ApiPublicEmergencyTestMirrorRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alt'
    | '/app'
    | '/attorney'
    | '/checkout'
    | '/coming-soon'
    | '/dag'
    | '/download'
    | '/intake'
    | '/login'
    | '/own-property'
    | '/partners'
    | '/pastors'
    | '/privacy'
    | '/retainer'
    | '/sentinel-trust'
    | '/sitemap.xml'
    | '/splash'
    | '/support'
    | '/unsubscribe'
    | '/venues'
    | '/admin'
    | '/cases'
    | '/dashboard'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/readiness/intake'
    | '/readiness/review'
    | '/readiness/sign'
    | '/readiness/start'
    | '/track/$token'
    | '/admin/clients'
    | '/admin/reminders'
    | '/admin/triggers'
    | '/case/$id'
    | '/firm/queue'
    | '/api/public/mail-from-check'
    | '/api/public/send-admin-invite'
    | '/lovable/email/suppression'
    | '/admin/clients/$id'
    | '/firm/review/$id'
    | '/api/public/cron/process-due-activations'
    | '/api/public/dev/send-install'
    | '/api/public/emergency/activate'
    | '/api/public/emergency/test-mirror'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alt'
    | '/app'
    | '/attorney'
    | '/checkout'
    | '/coming-soon'
    | '/dag'
    | '/download'
    | '/intake'
    | '/login'
    | '/own-property'
    | '/partners'
    | '/pastors'
    | '/privacy'
    | '/retainer'
    | '/sentinel-trust'
    | '/sitemap.xml'
    | '/splash'
    | '/support'
    | '/unsubscribe'
    | '/venues'
    | '/admin'
    | '/cases'
    | '/dashboard'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/readiness/intake'
    | '/readiness/review'
    | '/readiness/sign'
    | '/readiness/start'
    | '/track/$token'
    | '/admin/clients'
    | '/admin/reminders'
    | '/admin/triggers'
    | '/case/$id'
    | '/firm/queue'
    | '/api/public/mail-from-check'
    | '/api/public/send-admin-invite'
    | '/lovable/email/suppression'
    | '/admin/clients/$id'
    | '/firm/review/$id'
    | '/api/public/cron/process-due-activations'
    | '/api/public/dev/send-install'
    | '/api/public/emergency/activate'
    | '/api/public/emergency/test-mirror'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_firm'
    | '/alt'
    | '/app'
    | '/attorney'
    | '/checkout'
    | '/coming-soon'
    | '/dag'
    | '/download'
    | '/intake'
    | '/login'
    | '/own-property'
    | '/partners'
    | '/pastors'
    | '/privacy'
    | '/retainer'
    | '/sentinel-trust'
    | '/sitemap.xml'
    | '/splash'
    | '/support'
    | '/unsubscribe'
    | '/venues'
    | '/_admin/admin'
    | '/_authenticated/cases'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/readiness/intake'
    | '/readiness/review'
    | '/readiness/sign'
    | '/readiness/start'
    | '/track/$token'
    | '/_admin/admin/clients'
    | '/_admin/admin/reminders'
    | '/_admin/admin/triggers'
    | '/_authenticated/case/$id'
    | '/_firm/firm/queue'
    | '/api/public/mail-from-check'
    | '/api/public/send-admin-invite'
    | '/lovable/email/suppression'
    | '/_admin/admin/clients/$id'
    | '/_firm/firm/review/$id'
    | '/api/public/cron/process-due-activations'
    | '/api/public/dev/send-install'
    | '/api/public/emergency/activate'
    | '/api/public/emergency/test-mirror'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FirmRoute: typeof FirmRouteWithChildren
  AltRoute: typeof AltRoute
  AppRoute: typeof AppRoute
  AttorneyRoute: typeof AttorneyRoute
  CheckoutRoute: typeof CheckoutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DagRoute: typeof DagRoute
  DownloadRoute: typeof DownloadRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  OwnPropertyRoute: typeof OwnPropertyRoute
  PartnersRoute: typeof PartnersRoute
  PastorsRoute: typeof PastorsRoute
  PrivacyRoute: typeof PrivacyRoute
  RetainerRoute: typeof RetainerRoute
  SentinelTrustRoute: typeof SentinelTrustRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SplashRoute: typeof SplashRoute
  SupportRoute: typeof SupportRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VenuesRoute: typeof VenuesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ReadinessIntakeRoute: typeof ReadinessIntakeRoute
  ReadinessReviewRoute: typeof ReadinessReviewRoute
  ReadinessSignRoute: typeof ReadinessSignRoute
  ReadinessStartRoute: typeof ReadinessStartRoute
  TrackTokenRoute: typeof TrackTokenRoute
  ApiPublicMailFromCheckRoute: typeof ApiPublicMailFromCheckRoute
  ApiPublicSendAdminInviteRoute: typeof ApiPublicSendAdminInviteRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronProcessDueActivationsRoute: typeof ApiPublicCronProcessDueActivationsRoute
  ApiPublicDevSendInstallRoute: typeof ApiPublicDevSendInstallRoute
  ApiPublicEmergencyActivateRoute: typeof ApiPublicEmergencyActivateRoute
  ApiPublicEmergencyTestMirrorRoute: typeof ApiPublicEmergencyTestMirrorRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinel-trust': {
      id: '/sentinel-trust'
      path: '/sentinel-trust'
      fullPath: '/sentinel-trust'
      preLoaderRoute: typeof SentinelTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retainer': {
      id: '/retainer'
      path: '/retainer'
      fullPath: '/retainer'
      preLoaderRoute: typeof RetainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastors': {
      id: '/pastors'
      path: '/pastors'
      fullPath: '/pastors'
      preLoaderRoute: typeof PastorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/own-property': {
      id: '/own-property'
      path: '/own-property'
      fullPath: '/own-property'
      preLoaderRoute: typeof OwnPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dag': {
      id: '/dag'
      path: '/dag'
      fullPath: '/dag'
      preLoaderRoute: typeof DagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attorney': {
      id: '/attorney'
      path: '/attorney'
      fullPath: '/attorney'
      preLoaderRoute: typeof AttorneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alt': {
      id: '/alt'
      path: '/alt'
      fullPath: '/alt'
      preLoaderRoute: typeof AltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_firm': {
      id: '/_firm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/start': {
      id: '/readiness/start'
      path: '/readiness/start'
      fullPath: '/readiness/start'
      preLoaderRoute: typeof ReadinessStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/sign': {
      id: '/readiness/sign'
      path: '/readiness/sign'
      fullPath: '/readiness/sign'
      preLoaderRoute: typeof ReadinessSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/review': {
      id: '/readiness/review'
      path: '/readiness/review'
      fullPath: '/readiness/review'
      preLoaderRoute: typeof ReadinessReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/intake': {
      id: '/readiness/intake'
      path: '/readiness/intake'
      fullPath: '/readiness/intake'
      preLoaderRoute: typeof ReadinessIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-admin-invite': {
      id: '/api/public/send-admin-invite'
      path: '/api/public/send-admin-invite'
      fullPath: '/api/public/send-admin-invite'
      preLoaderRoute: typeof ApiPublicSendAdminInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mail-from-check': {
      id: '/api/public/mail-from-check'
      path: '/api/public/mail-from-check'
      fullPath: '/api/public/mail-from-check'
      preLoaderRoute: typeof ApiPublicMailFromCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_firm/firm/queue': {
      id: '/_firm/firm/queue'
      path: '/firm/queue'
      fullPath: '/firm/queue'
      preLoaderRoute: typeof FirmFirmQueueRouteImport
      parentRoute: typeof FirmRoute
    }
    '/_authenticated/case/$id': {
      id: '/_authenticated/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof AuthenticatedCaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin/triggers': {
      id: '/_admin/admin/triggers'
      path: '/triggers'
      fullPath: '/admin/triggers'
      preLoaderRoute: typeof AdminAdminTriggersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reminders': {
      id: '/_admin/admin/reminders'
      path: '/reminders'
      fullPath: '/admin/reminders'
      preLoaderRoute: typeof AdminAdminRemindersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/clients': {
      id: '/_admin/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminAdminClientsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emergency/test-mirror': {
      id: '/api/public/emergency/test-mirror'
      path: '/api/public/emergency/test-mirror'
      fullPath: '/api/public/emergency/test-mirror'
      preLoaderRoute: typeof ApiPublicEmergencyTestMirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/emergency/activate': {
      id: '/api/public/emergency/activate'
      path: '/api/public/emergency/activate'
      fullPath: '/api/public/emergency/activate'
      preLoaderRoute: typeof ApiPublicEmergencyActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dev/send-install': {
      id: '/api/public/dev/send-install'
      path: '/api/public/dev/send-install'
      fullPath: '/api/public/dev/send-install'
      preLoaderRoute: typeof ApiPublicDevSendInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-due-activations': {
      id: '/api/public/cron/process-due-activations'
      path: '/api/public/cron/process-due-activations'
      fullPath: '/api/public/cron/process-due-activations'
      preLoaderRoute: typeof ApiPublicCronProcessDueActivationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_firm/firm/review/$id': {
      id: '/_firm/firm/review/$id'
      path: '/firm/review/$id'
      fullPath: '/firm/review/$id'
      preLoaderRoute: typeof FirmFirmReviewIdRouteImport
      parentRoute: typeof FirmRoute
    }
    '/_admin/admin/clients/$id': {
      id: '/_admin/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminAdminClientsIdRouteImport
      parentRoute: typeof AdminAdminClientsRoute
    }
  }
}

interface AdminAdminClientsRouteChildren {
  AdminAdminClientsIdRoute: typeof AdminAdminClientsIdRoute
}

const AdminAdminClientsRouteChildren: AdminAdminClientsRouteChildren = {
  AdminAdminClientsIdRoute: AdminAdminClientsIdRoute,
}

const AdminAdminClientsRouteWithChildren =
  AdminAdminClientsRoute._addFileChildren(AdminAdminClientsRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminClientsRoute: typeof AdminAdminClientsRouteWithChildren
  AdminAdminRemindersRoute: typeof AdminAdminRemindersRoute
  AdminAdminTriggersRoute: typeof AdminAdminTriggersRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminClientsRoute: AdminAdminClientsRouteWithChildren,
  AdminAdminRemindersRoute: AdminAdminRemindersRoute,
  AdminAdminTriggersRoute: AdminAdminTriggersRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCaseIdRoute: typeof AuthenticatedCaseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCaseIdRoute: AuthenticatedCaseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface FirmRouteChildren {
  FirmFirmQueueRoute: typeof FirmFirmQueueRoute
  FirmFirmReviewIdRoute: typeof FirmFirmReviewIdRoute
}

const FirmRouteChildren: FirmRouteChildren = {
  FirmFirmQueueRoute: FirmFirmQueueRoute,
  FirmFirmReviewIdRoute: FirmFirmReviewIdRoute,
}

const FirmRouteWithChildren = FirmRoute._addFileChildren(FirmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FirmRoute: FirmRouteWithChildren,
  AltRoute: AltRoute,
  AppRoute: AppRoute,
  AttorneyRoute: AttorneyRoute,
  CheckoutRoute: CheckoutRoute,
  ComingSoonRoute: ComingSoonRoute,
  DagRoute: DagRoute,
  DownloadRoute: DownloadRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  OwnPropertyRoute: OwnPropertyRoute,
  PartnersRoute: PartnersRoute,
  PastorsRoute: PastorsRoute,
  PrivacyRoute: PrivacyRoute,
  RetainerRoute: RetainerRoute,
  SentinelTrustRoute: SentinelTrustRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SplashRoute: SplashRoute,
  SupportRoute: SupportRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VenuesRoute: VenuesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ReadinessIntakeRoute: ReadinessIntakeRoute,
  ReadinessReviewRoute: ReadinessReviewRoute,
  ReadinessSignRoute: ReadinessSignRoute,
  ReadinessStartRoute: ReadinessStartRoute,
  TrackTokenRoute: TrackTokenRoute,
  ApiPublicMailFromCheckRoute: ApiPublicMailFromCheckRoute,
  ApiPublicSendAdminInviteRoute: ApiPublicSendAdminInviteRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronProcessDueActivationsRoute:
    ApiPublicCronProcessDueActivationsRoute,
  ApiPublicDevSendInstallRoute: ApiPublicDevSendInstallRoute,
  ApiPublicEmergencyActivateRoute: ApiPublicEmergencyActivateRoute,
  ApiPublicEmergencyTestMirrorRoute: ApiPublicEmergencyTestMirrorRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
